version: '3.8'

services:
  app:
    build:
      context: . # Builds the Dockerfile in the current directory
    ports:
      - "3000:3000" # Expose port 5000 on the host machine
    environment:
      - MONGO_URI=${MONGO_URI}  # Using MONGO_URI from the .env file

