apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: addtocart
  name: addtocart
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: vrbko/addtocart:latest
      name: latest
      referencePolicy:
        type: ""
