apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: cart
  name: cart
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: vrbko/cart:latest
      name: latest
      referencePolicy:
        type: ""
