apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: cart
  name: cart
spec:
  ports:
    - name: "3002"
      port: 3002
      targetPort: 3002
  selector:
    io.kompose.service: cart
