version: '3.8'

services:

  home:
    image: vrbko/home:latest
    ports:
      - "2999:2999"
    restart: always

  pdp:
    image: vrbko/pdp:latest
    ports:
      - "3001:3001"
    restart: always

  cart:
    image: vrbko/cart:latest
    ports:
      - "3002:3002"
    restart: always

  addtocart:
    image: vrbko/addtocart:latest
    ports:
      - "3003:3003"
    restart: always

  server:
    image: vrbko/server:latest
    ports:
      - "8080:8080"
    restart: always

