apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: home
  name: home
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: vrbko/home:latest
      name: latest
      referencePolicy:
        type: ""
