apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: home
  name: home
spec:
  ports:
    - name: "2999"
      port: 2999
      targetPort: 2999
  selector:
    io.kompose.service: home
