apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    io.kompose.service: narocanje
  name: narocanje
spec:
  replicas: 1
  selector:
    io.kompose.service: narocanje
  template:
    metadata:
      labels:
        io.kompose.service: narocanje
    spec:
      containers:
        - image: ' '
          name: php-app
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - php-app
        from:
          kind: ImageStreamTag
          name: narocanje:latest
      type: ImageChange
