apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: pdp
  name: pdp
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    io.kompose.service: pdp
