apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: pdp
  name: pdp
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: vrbko/pdp:latest
      name: latest
      referencePolicy:
        type: ""
