apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: php
  name: php
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
  selector:
    io.kompose.service: php
