apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: redis:latest
      name: latest
      referencePolicy:
        type: ""
