apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: server
  name: server
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: vrbko/server:latest
      name: latest
      referencePolicy:
        type: ""
