apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: uporabniki
  name: uporabniki
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: vrbko/uporabniki:latest
      name: latest
      referencePolicy:
        type: ""
