apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: zaloga
  name: zaloga
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: vrbko/zaloga:latest
      name: latest
      referencePolicy:
        type: ""
