name: Test gRPC Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_grpc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip==25.0.1
        pip install setuptools==77.0.3
        pip install grpcio==1.71.0
        pip install grpcio-tools==1.71.0
        pip install protobuf==5.29.4
        pip install bcrypt==4.3.0
        pip install SQLAlchemy==2.0.39
        pip install typing_extensions==4.12.2
        pip install pytest  # Install pytest

    - name: Run server (in background)
      run: |
        nohup python server.py &  # Run the server in the background
        sleep 10  # Wait for the server to start

    - name: Run tests
      run: |
        pytest Storitev_Uporabniki/test/test_server.py  # Run the tests