name: PHP Redis Workflow Tests

on:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 6379:6379
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: redis, bcmath, mbstring, json, curl

    - name: Install Composer dependencies
      run: |
        cd Storitev_Narocanje
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install --no-progress --no-suggest

    - name: Run tests with PHPUnit
      run: |
        cd Storitev_Narocanje
        ./vendor/bin/phpunit tests/RedisWorkflowTest.php
      env:
        REDIS_HOST: localhost
        REDIS_PORT: 6379