# Ime pipeline-a za backend
name: Backend CI

# Dogodki, ki sprožijo workflow (push in pull request na glavno vejo)
on:
  push:
    branches:
      - main

jobs:
  # Job za gradnjo backenda
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code  # Kloniranje repozitorija
      uses: actions/checkout@v3

    - name: Setup Node.js  # Namestitev Node.js okolja
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # Inject the MongoDB URI from GitHub secrets
    - name: Set environment variables
      run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

    - name: Cache node_modules  # Caching odvisnosti
      uses: actions/cache@v3
      with:
        path: Storitev_Zaloga/node_modules  # Pot do mape node_modules
        key: ${{ runner.os }}-backend-${{ hashFiles('Storitev_Zaloga/package-lock.json') }}  # Ključ za cache
        restore-keys: |
          ${{ runner.os }}-backend-

    - name: Install dependencies  # Namestitev odvisnosti
      run: |
        cd Storitev_Zaloga
        npm ci

    - name: Upload backend artifacts  # Naložitev artefaktov za backend
      uses: actions/upload-artifact@v4
      with:
        name: backend-build  # Ime artefakta
        path: |
          Storitev_Zaloga/  
          Storitev_Zaloga/node_modules/  
        # Pot do celotne kode
        # Nameščene odvisnosti

  # Job za testiranje backenda
  test-backend:
    needs: build-backend  # Testiranje se izvede po uspešni gradnji
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code  # Kloniranje repozitorija
      uses: actions/checkout@v3

    - name: Setup Node.js  # Namestitev Node.js okolja
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Cache node_modules  # Caching odvisnosti
      uses: actions/cache@v3
      with:
        path: Storitev_Zaloga/node_modules  # Pot do mape node_modules
        key: ${{ runner.os }}-backend-${{ hashFiles('Storitev_Zaloga/package-lock.json') }}  # Ključ za cache
        restore-keys: |
          ${{ runner.os }}-backend-

    - name: Set environment variables
      run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
      
    - name: Install dependencies  # Namestitev odvisnosti
      run: |
        cd Storitev_Zaloga
        npm install

    - name: Run tests with coverage  # Izvajanje testov s pokritostjo
      run: |
        cd Storitev_Zaloga
        npm run test:ci --forceExit

    - name: Upload coverage report  # Naložitev poročila o pokritosti kode
      uses: actions/upload-artifact@v4
      with:
        name: backend-coverage  # Ime artefakta
        path: Storitev_Zaloga/coverage/  # Pot do poročila o pokritosti kode


