name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io  # Docker Hub registry
      IMAGE_OWNER: vrbko   # Docker Hub username

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push home image
        uses: docker/build-push-action@v5
        with:
          context: ./UporabnskiVmesnik/home
          file: ./UporabnskiVmesnik/home/Dockerfile  # Explicit path to Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/home:latest

      - name: Build and push pdp image
        uses: docker/build-push-action@v5
        with:
          context: ./UporabnskiVmesnik/pdp
          file: ./UporabnskiVmesnik/pdp/Dockerfile  # Explicit path to Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/pdp:latest

      - name: Build and push cart image
        uses: docker/build-push-action@v5
        with:
          context: ./UporabnskiVmesnik/cart
          file: ./UporabnskiVmesnik/cart/Dockerfile  # Explicit path to Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/cart:latest

      - name: Build and push addtocart image
        uses: docker/build-push-action@v5
        with:
          context: ./UporabnskiVmesnik/addtocart
          file: ./UporabnskiVmesnik/addtocart/Dockerfile  # Explicit path to Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/addtocart:latest

      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: ./UporabnskiVmesnik/server
          file: ./UporabnskiVmesnik/server/Dockerfile  # Explicit path to Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/server:latest

      - name: Build and push zaloga image
        uses: docker/build-push-action@v5
        with:
          context: ./Storitev_Zaloga/
          file: ./Storitev_Zaloga/Dockerfile  # Explicit path to Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/zaloga:latest

      - name: Build and push uporabniki image
        uses: docker/build-push-action@v5
        with:
          context: ./Storitev_Uporabniki/
          file: ./Storitev_Uporabniki/Dockerfile  # Explicit path to Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/uporabniki:latest

      - name: Build and push narocanje image
        uses: docker/build-push-action@v5
        with:
          context: ./Storitev_Narocanje/
          file: ./Storitev_Narocanje/Dockerfile  # Explicit path to Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/narocanje:latest